#! /bin/sh

bspc monitor -d 1 2 3

bspc config border_width 		2
bspc config window_gap 			10
bspc config bottom_padding 		21
bspc config pointer_modifier
bspc config focus_follows_pointer	true

bspc config split_ratio			0.50
bspc config borderless_monocle 		true
bspc config gapless_monocle 		true
bspc config auto_cancel 		true

bspc config normal_border_color 	"#47474b"
bspc config focused_border_color 	"#96b8c7"
