/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBGUS_(disc_1)_01_-_Tuscan_Leather_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBILK_(disc_1)_02_-_Furthest_Thing_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBK68_(disc_1)_03_-_Started_From_The_Bottom_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBLPI_(disc_1)_04_-_Wu-Tang_Forever_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBN3S_(disc_1)_05_-_Own_It_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBOL4_(disc_1)_06_-_Worst_Behavior_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBQ7Q_(disc_1)_07_-_From_Time_[feat__Jhené_Aiko]_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBSAG_(disc_1)_08_-_Hold_On,_We're_Going_Home_[feat__Majid_J.mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBTMI_(disc_1)_09_-_Connect_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBUVI_(disc_1)_10_-_The_Language_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBW70_(disc_1)_11_-_305_To_My_City_[feat__Detail]_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBXTC_(disc_1)_12_-_Too_Much_[feat__Sampha]_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FBZ9U_(disc_1)_13_-_Pound_Cake___Paris_Morton_Music_2_[feat_.mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FC1NE_(disc_1)_14_-_Come_Thru_[Explicit].mp3
/Users/prxy/Music/Nothing_Was_The_Same_(Deluxe)_[Explicit]/B00F5FCBNO_(disc_1)_15_-_All_Me_[feat__2_Chainz,_Big_Sean]_[Expli.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B1AKPM_(disc_1)_01_-_Red_Intro.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B19AT4_(disc_1)_02_-_How_Many_Mics.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B172N0_(disc_1)_03_-_Ready_Or_Not.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B19ATY_(disc_1)_04_-_Zealots.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B172NU_(disc_1)_05_-_The_Beast.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B155NE_(disc_1)_06_-_Fu-Gee-La_[Explicit].mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B19ASK_(disc_1)_07_-_Family_Business.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B1CCDK_(disc_1)_08_-_Killing_Me_Softly_With_His_Song.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B1CCE4_(disc_1)_09_-_The_Score.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B155NO_(disc_1)_10_-_The_Mask.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B172MQ_(disc_1)_11_-_Cowboys.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B155NY_(disc_1)_12_-_No_Woman,_No_Cry.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B19ATE_(disc_1)_13_-_Manifest_Outro.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B19ASU_(disc_1)_14_-_Fu-Gee-La_(Refugee_Camp_Remix).mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B1CCD0_(disc_1)_15_-_Fu-Gee-La_(Sly_&_Robbie_Mix).mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B172NA_(disc_1)_16_-_Mista_Mista.mp3
/Users/prxy/Music/Fugees/The_Score_[Explicit]/B001B155OI_(disc_1)_17_-_Fu-Gee-La_(Refugee_Camp_Global_Mix).mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV14K_(disc_1)_01_-_Intro_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV168_(disc_1)_02_-_Dollar_And_A_Dream_III_(Explicit_Version.mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1G8_(disc_1)_03_-_Can't_Get_Enough_(Explicit_Version)_[Exp.mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1MC_(disc_1)_04_-_Lights_Please_(Explicit_Version)_[Explic.mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1OA_(disc_1)_05_-_Interlude_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1RM_(disc_1)_06_-_Sideline_Story_(Explicit_Version)_[Expli.mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1VS_(disc_1)_07_-_Mr__Nice_Watch_(Explicit_Version)_[Expli.mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1YA_(disc_1)_08_-_Cole_World_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV1ZY_(disc_1)_09_-_In_The_Morning_(Explicit_Version).mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV230_(disc_1)_10_-_Lost_Ones_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV2A8_(disc_1)_11_-_Nobody's_Perfect_(Explicit_Version)_[Exp.mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV2C6_(disc_1)_12_-_Never_Told_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV2GM_(disc_1)_13_-_Rise_And_Shine_(Explicit_Version).mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV2LW_(disc_1)_14_-_God's_Gift_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV2Q2_(disc_1)_15_-_Breakdown_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/Cole_World__The_Sideline_Story_[Explicit]/B005OKV2RG_(disc_1)_16_-_Work_Out_(Explicit_Version)_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHY51E_(disc_1)_01_-_Intro_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHY6S6_(disc_1)_02_-_January_28th_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHY898_(disc_1)_03_-_Wet_Dreamz_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHY9WO_(disc_1)_04_-_03'_Adolescence_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYBAY_(disc_1)_05_-_A_Tale_of_2_Citiez_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYCX0_(disc_1)_06_-_Fire_Squad_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYE7E_(disc_1)_07_-_St__Tropez_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYG1S_(disc_1)_08_-_G_O_M_D__[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYHTE_(disc_1)_09_-_No_Role_Modelz_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYP3M_(disc_1)_10_-_Hello_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYQWM_(disc_1)_11_-_Apparently_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYXWA_(disc_1)_12_-_Love_Yourz_[Explicit].mp3
/Users/prxy/Music/2014_Forest_Hills_Drive_[Explicit]/B00PJHYZ8M_(disc_1)_13_-_Note_to_Self_[Explicit].mp3
/Users/prxy/Music/The_College_Dropout/B000VZO730_(disc_1)_01_-_Intro_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZLO6S_(disc_1)_02_-_We_Don't_Care_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZLO8G_(disc_1)_03_-_Graduation_Day_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZJQKY_(disc_1)_04_-_All_Falls_Down_(Explicit)_[feat__Syleena.mp3
/Users/prxy/Music/The_College_Dropout/B000VZO758_(disc_1)_05_-_I'll_Fly_Away_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZPFWM_(disc_1)_06_-_Spaceship_(Explicit)_[feat__GLC,_Consequ.mp3
/Users/prxy/Music/The_College_Dropout/B000VZPFX6_(disc_1)_07_-_Jesus_Walks_[Explicit].mp3
/Users/prxy/Music/The_College_Dropout/B000VZPFY0_(disc_1)_08_-_Never_Let_Me_Down_(Explicit)_[feat__JAY-.mp3
/Users/prxy/Music/The_College_Dropout/B000VZRB56_(disc_1)_09_-_Get_Em_High_(Explicit)_[feat__Talib_Kwel.mp3
/Users/prxy/Music/The_College_Dropout/B000VZLOCW_(disc_1)_10_-_Workout_Plan_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZO794_(disc_1)_11_-_The_New_Workout_Plan_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZO7AS_(disc_1)_12_-_Slow_Jamz_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZO7BC_(disc_1)_13_-_Breathe_In_Breathe_Out_(Explicit)_[feat_.mp3
/Users/prxy/Music/The_College_Dropout/B000VZRBA6_(disc_1)_14_-_School_Spirit_Skit_1_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZPG1C_(disc_1)_15_-_School_Spirit.mp3
/Users/prxy/Music/The_College_Dropout/B000VZLOG8_(disc_1)_16_-_School_Spirit_Skit_2_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZO7DA_(disc_1)_17_-_Lil_Jimmy_Skit_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZLOHM_(disc_1)_18_-_Two_Words_(Explicit)_[feat__Mos_Def,_Fre.mp3
/Users/prxy/Music/The_College_Dropout/B000VZLOI6_(disc_1)_19_-_Through_The_Wire_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZO7G2_(disc_1)_20_-_Family_Business_(Explicit).mp3
/Users/prxy/Music/The_College_Dropout/B000VZRBH4_(disc_1)_21_-_Last_Call_(Explicit).mp3
/Users/prxy/Music/Late_Registration/B000VZJMWQ_(disc_1)_01_-_Wake_Up_Mr__West_(Explicit).mp3
/Users/prxy/Music/Late_Registration/B000VZO3MU_(disc_1)_02_-_Heard_'Em_Say_(Explicit)_[feat__Adam_Lev.mp3
/Users/prxy/Music/Late_Registration/B000VZLKQM_(disc_1)_03_-_Touch_The_Sky_(Explicit)_[feat__Lupe_Fia.mp3
/Users/prxy/Music/Late_Registration/B000VZO3NO_(disc_1)_04_-_Gold_Digger_(Explicit)_[feat__Jamie_Foxx.mp3
/Users/prxy/Music/Late_Registration/B000VZJN1G_(disc_1)_05_-_Skit__1_(Kanye_West_Late_Registration)_(.mp3
/Users/prxy/Music/Late_Registration/B000VZLKSU_(disc_1)_06_-_Drive_Slow_(Explicit)_[feat__Paul_Wall,_.mp3
/Users/prxy/Music/Late_Registration/B000VZO3PC_(disc_1)_07_-_My_Way_Home_(Explicit)_[feat__Common].mp3
/Users/prxy/Music/Late_Registration/B000VZR7KK_(disc_1)_08_-_Crack_Music_(Explicit)_[feat__The_Game].mp3
/Users/prxy/Music/Late_Registration/B000VZR7LY_(disc_1)_09_-_Roses_(Explicit).mp3
/Users/prxy/Music/Late_Registration/B000VZR7MI_(disc_1)_10_-_Bring_Me_Down_(Explicit)_[feat__Brandy].mp3
/Users/prxy/Music/Late_Registration/B000VZR7N2_(disc_1)_11_-_Addiction_(Explicit).mp3
/Users/prxy/Music/Late_Registration/B000VZJN4S_(disc_1)_12_-_Skit__2_(Kanye_West_Late_Registration)_(.mp3
/Users/prxy/Music/Late_Registration/B000VZR7OQ_(disc_1)_13_-_Diamonds_From_Sierra_Leone_(Remix)_(Expl.mp3
/Users/prxy/Music/Late_Registration/B000VZJN5W_(disc_1)_14_-_We_Major_(Explicit)_[feat__Nas,_Really_D.mp3
/Users/prxy/Music/Late_Registration/B000VZJN6Q_(disc_1)_15_-_Skit__3_(Kanye_West_Late_Registration)_(.mp3
/Users/prxy/Music/Late_Registration/B000VZJN7K_(disc_1)_16_-_Hey_Mama_(Explicit).mp3
/Users/prxy/Music/Late_Registration/B000VZO3W0_(disc_1)_17_-_Celebration_(Explicit).mp3
/Users/prxy/Music/Late_Registration/B000VZLKYO_(disc_1)_18_-_Skit__4_(Kanye_West_Late_Registration)_(.mp3
/Users/prxy/Music/Late_Registration/B000VZO3WU_(disc_1)_19_-_Gone_(Explicit)_[feat__Consequence,_Cam'.mp3
/Users/prxy/Music/Late_Registration/B000VZPCCU_(disc_1)_20_-___Bonus_Track___Diamonds_From_Sierra_Leo.mp3
/Users/prxy/Music/Late_Registration/B000VZJNBQ_(disc_1)_21_-_Late_(Explicit).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXRFUK_(disc_1)_01_-_In_My_Dreams_(Cudder_Anthem)_(Album_Vers.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLJM_(disc_1)_02_-_Soundtrack_2_My_Life_(Album_Version_(Exp.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLLK_(disc_1)_03_-_Simple_As____(Album_Version_(Explicit)).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMK46_(disc_1)_04_-_Solo_Dolo_(Nightmare)_[Explicit].mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMK50_(disc_1)_05_-_Heart_Of_A_Lion_(Kid_Cudi_Theme_Music)_(.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXRFZU_(disc_1)_06_-_My_World_(Album_Version_(Explicit))_[fea.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLQK_(disc_1)_07_-_Day_'N'_Nite_(Nightmare).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXOJTA_(disc_1)_08_-_Sky_Might_Fall_(Album_Version_(Explicit).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLSI_(disc_1)_09_-_Enter_Galactic_(Love_Connection_Part_I)_.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXPTNK_(disc_1)_10_-_Alive_(Nightmare)_[Explicit].mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXRG5E_(disc_1)_11_-_Cudi_Zone_(Album_Version_(Explicit)).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMKC8_(disc_1)_12_-_Make_Her_Say_(Album_Version_(Explicit))_.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLYW_(disc_1)_13_-_Pursuit_Of_Happiness_(Nightmare)_[Explic.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMKEG_(disc_1)_14_-_Hyyerr_(Album_Version_(Explicit))_[feat_.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXIMZ2_(disc_1)_15_-_Up_Up_&_Away_(Album_Version_(Explicit)).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE7BA_(disc_1)_01_-_The_Resurrection_Of_Scott_Mescudi_[Expli.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE7QK_(disc_1)_02_-_Unfuckwittable_[Explicit].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE8A0_(disc_1)_03_-_Just_What_I_Am_(Explicit_Version)_[feat_.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE8N2_(disc_1)_04_-_Young_Lady_[feat__Father_John_Misty]_[Ex.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE904_(disc_1)_05_-_King_Wizard_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE9E0_(disc_1)_06_-_Immortal_[Explicit].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE9RW_(disc_1)_07_-_Solo_Dolo_Part_II_(Explicit_Version)_[fe.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEA8A_(disc_1)_08_-_Girls_(Explicit_Version)_[feat__Too_$hor.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEAS0_(disc_1)_09_-_New_York_City_Rage_Fest_(Explicit_Versio.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEB66_(disc_1)_10_-_Red_Eye_(Explicit_Version)_[feat__Haïm].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEBLG_(disc_1)_11_-_Mad_Solar_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEBWK_(disc_1)_12_-_Beez_(Explicit_Version)_[feat__RZA].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGECKG_(disc_1)_13_-_Brothers_(Explicit_Version)_[feat__King_.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGECZ6_(disc_1)_14_-_Burn_Baby_Burn_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEDF0_(disc_1)_15_-_Lord_Of_The_Sad_And_Lonely_(Explicit_Ver.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEDPU_(disc_1)_16_-_Cold_Blooded_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEEAE_(disc_1)_17_-_Afterwards_(Bring_Yo_Friends)_(Explicit_.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEER2_(disc_1)_18_-_The_Flight_Of_The_Moon_Man_(Explicit_Ver.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GF9C_(disc_1)_01_-_Sacrilegious_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GFUQ_(disc_1)_02_-_There_He_Go_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GG5U_(disc_1)_03_-_Hands_On_the_Wheel_(feat__a$Ap_Rocky)_[E.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGCS_(disc_1)_04_-_Sex_Drive_(feat__J_Hene_Aiko)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGN2_(disc_1)_05_-_Oxy_Music_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GH6I_(disc_1)_06_-_My_Hatin'_Joint_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHH2_(disc_1)_07_-_Tookie_Knows_(Interlude)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHVI_(disc_1)_08_-_Raymond_1969_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GINA_(disc_1)_09_-_Sexting_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GIZS_(disc_1)_10_-_Grooveline_Pt__1_(feat__Dom_Kennedy_&_Cu.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJ9S_(disc_1)_11_-_Gangsta_In_Designer_(No_Concept)_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJJS_(disc_1)_12_-_How_We_Feeling_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJUW_(disc_1)_13_-_Druggys_Wit_Hoes_Again_(feat__Ab_Soul)_[.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GK6A_(disc_1)_14_-_Nightmare_On_Figg_St__[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKHY_(disc_1)_15_-_My_Homie_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKTM_(disc_1)_16_-_Blessed_(feat__Kendrick_Lamar)_[Explicit.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GL2I_(disc_1)_17_-_NiggaHs_Already_Know_Davers_Flow_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GLFU_(disc_1)_18_-_2_Raw_(feat__Jay_Rock)_[Explicit].mp3
