/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GF9C_(disc_1)_01_-_Sacrilegious_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GFUQ_(disc_1)_02_-_There_He_Go_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GG5U_(disc_1)_03_-_Hands_On_the_Wheel_(feat__a$Ap_Rocky)_[E.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGCS_(disc_1)_04_-_Sex_Drive_(feat__J_Hene_Aiko)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGN2_(disc_1)_05_-_Oxy_Music_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GH6I_(disc_1)_06_-_My_Hatin'_Joint_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHH2_(disc_1)_07_-_Tookie_Knows_(Interlude)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHVI_(disc_1)_08_-_Raymond_1969_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GINA_(disc_1)_09_-_Sexting_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GIZS_(disc_1)_10_-_Grooveline_Pt__1_(feat__Dom_Kennedy_&_Cu.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJ9S_(disc_1)_11_-_Gangsta_In_Designer_(No_Concept)_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJJS_(disc_1)_12_-_How_We_Feeling_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJUW_(disc_1)_13_-_Druggys_Wit_Hoes_Again_(feat__Ab_Soul)_[.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GK6A_(disc_1)_14_-_Nightmare_On_Figg_St__[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKHY_(disc_1)_15_-_My_Homie_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKTM_(disc_1)_16_-_Blessed_(feat__Kendrick_Lamar)_[Explicit.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GL2I_(disc_1)_17_-_NiggaHs_Already_Know_Davers_Flow_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GLFU_(disc_1)_18_-_2_Raw_(feat__Jay_Rock)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GF9C_(disc_1)_01_-_Sacrilegious_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GFUQ_(disc_1)_02_-_There_He_Go_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GG5U_(disc_1)_03_-_Hands_On_the_Wheel_(feat__a$Ap_Rocky)_[E.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGCS_(disc_1)_04_-_Sex_Drive_(feat__J_Hene_Aiko)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGN2_(disc_1)_05_-_Oxy_Music_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GH6I_(disc_1)_06_-_My_Hatin'_Joint_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHH2_(disc_1)_07_-_Tookie_Knows_(Interlude)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHVI_(disc_1)_08_-_Raymond_1969_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GINA_(disc_1)_09_-_Sexting_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GIZS_(disc_1)_10_-_Grooveline_Pt__1_(feat__Dom_Kennedy_&_Cu.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJ9S_(disc_1)_11_-_Gangsta_In_Designer_(No_Concept)_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJJS_(disc_1)_12_-_How_We_Feeling_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJUW_(disc_1)_13_-_Druggys_Wit_Hoes_Again_(feat__Ab_Soul)_[.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GK6A_(disc_1)_14_-_Nightmare_On_Figg_St__[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKHY_(disc_1)_15_-_My_Homie_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKTM_(disc_1)_16_-_Blessed_(feat__Kendrick_Lamar)_[Explicit.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GL2I_(disc_1)_17_-_NiggaHs_Already_Know_Davers_Flow_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GLFU_(disc_1)_18_-_2_Raw_(feat__Jay_Rock)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GF9C_(disc_1)_01_-_Sacrilegious_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GFUQ_(disc_1)_02_-_There_He_Go_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GG5U_(disc_1)_03_-_Hands_On_the_Wheel_(feat__a$Ap_Rocky)_[E.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGCS_(disc_1)_04_-_Sex_Drive_(feat__J_Hene_Aiko)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GGN2_(disc_1)_05_-_Oxy_Music_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GH6I_(disc_1)_06_-_My_Hatin'_Joint_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHH2_(disc_1)_07_-_Tookie_Knows_(Interlude)_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GHVI_(disc_1)_08_-_Raymond_1969_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GINA_(disc_1)_09_-_Sexting_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GIZS_(disc_1)_10_-_Grooveline_Pt__1_(feat__Dom_Kennedy_&_Cu.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJ9S_(disc_1)_11_-_Gangsta_In_Designer_(No_Concept)_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJJS_(disc_1)_12_-_How_We_Feeling_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GJUW_(disc_1)_13_-_Druggys_Wit_Hoes_Again_(feat__Ab_Soul)_[.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GK6A_(disc_1)_14_-_Nightmare_On_Figg_St__[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKHY_(disc_1)_15_-_My_Homie_[Explicit].mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GKTM_(disc_1)_16_-_Blessed_(feat__Kendrick_Lamar)_[Explicit.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GL2I_(disc_1)_17_-_NiggaHs_Already_Know_Davers_Flow_[Explic.mp3
/Users/prxy/Music/Habits_&_Contradictions_[Explicit]/B006X9GLFU_(disc_1)_18_-_2_Raw_(feat__Jay_Rock)_[Explicit].mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXRFUK_(disc_1)_01_-_In_My_Dreams_(Cudder_Anthem)_(Album_Vers.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLJM_(disc_1)_02_-_Soundtrack_2_My_Life_(Album_Version_(Exp.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLLK_(disc_1)_03_-_Simple_As____(Album_Version_(Explicit)).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMK46_(disc_1)_04_-_Solo_Dolo_(Nightmare)_[Explicit].mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMK50_(disc_1)_05_-_Heart_Of_A_Lion_(Kid_Cudi_Theme_Music)_(.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXRFZU_(disc_1)_06_-_My_World_(Album_Version_(Explicit))_[fea.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLQK_(disc_1)_07_-_Day_'N'_Nite_(Nightmare).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXOJTA_(disc_1)_08_-_Sky_Might_Fall_(Album_Version_(Explicit).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLSI_(disc_1)_09_-_Enter_Galactic_(Love_Connection_Part_I)_.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXPTNK_(disc_1)_10_-_Alive_(Nightmare)_[Explicit].mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXRG5E_(disc_1)_11_-_Cudi_Zone_(Album_Version_(Explicit)).mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMKC8_(disc_1)_12_-_Make_Her_Say_(Album_Version_(Explicit))_.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXKLYW_(disc_1)_13_-_Pursuit_Of_Happiness_(Nightmare)_[Explic.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXMKEG_(disc_1)_14_-_Hyyerr_(Album_Version_(Explicit))_[feat_.mp3
/Users/prxy/Music/Man_On_The_Moon__The_End_Of_Day_(Explicit_Version)/B002NXIMZ2_(disc_1)_15_-_Up_Up_&_Away_(Album_Version_(Explicit)).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE7BA_(disc_1)_01_-_The_Resurrection_Of_Scott_Mescudi_[Expli.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE7QK_(disc_1)_02_-_Unfuckwittable_[Explicit].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE8A0_(disc_1)_03_-_Just_What_I_Am_(Explicit_Version)_[feat_.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE8N2_(disc_1)_04_-_Young_Lady_[feat__Father_John_Misty]_[Ex.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE904_(disc_1)_05_-_King_Wizard_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE9E0_(disc_1)_06_-_Immortal_[Explicit].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGE9RW_(disc_1)_07_-_Solo_Dolo_Part_II_(Explicit_Version)_[fe.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEA8A_(disc_1)_08_-_Girls_(Explicit_Version)_[feat__Too_$hor.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEAS0_(disc_1)_09_-_New_York_City_Rage_Fest_(Explicit_Versio.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEB66_(disc_1)_10_-_Red_Eye_(Explicit_Version)_[feat__Haïm].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEBLG_(disc_1)_11_-_Mad_Solar_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEBWK_(disc_1)_12_-_Beez_(Explicit_Version)_[feat__RZA].mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGECKG_(disc_1)_13_-_Brothers_(Explicit_Version)_[feat__King_.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGECZ6_(disc_1)_14_-_Burn_Baby_Burn_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEDF0_(disc_1)_15_-_Lord_Of_The_Sad_And_Lonely_(Explicit_Ver.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEDPU_(disc_1)_16_-_Cold_Blooded_(Explicit_Version).mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEEAE_(disc_1)_17_-_Afterwards_(Bring_Yo_Friends)_(Explicit_.mp3
/Users/prxy/Music/Indicud_(Explicit_Version)/B00CAGEER2_(disc_1)_18_-_The_Flight_Of_The_Moon_Man_(Explicit_Ver.mp3
/Users/prxy/Music/Late_Registration/B000VZR7KK_(disc_1)_08_-_Crack_Music_(Explicit)_[feat__The_Game].mp3
